{
    "id": 2,
    "status": 30,
    "attempts": 3,
    "create_time": "2024-01-09T03:57:45.726920+00:00",
    "update_time": "2024-01-09T03:57:46.629884+00:00",
    "lock": null,
    "lock_time": "2024-01-09T03:57:46.625141+00:00",
    "lock_expire_time": "2024-01-09T03:57:56.625141+00:00",
    "data": {},
    "errors": {
        "error": "TaskError('task failed')",
        "traceback": "Traceback (most recent call last):\n  File \"/Users/sanhehu/Documents/GitHub/abstract_tracker-project/abstract_tracker/base.py\", line 363, in start\n    yield self\n  File \"/var/folders/3y/7t5ll4sn6x76g8rhfqlc36dw0000gn/T/ipykernel_3549/1894269443.py\", line 2, in <module>\n    run_bad_task()\n  File \"/var/folders/3y/7t5ll4sn6x76g8rhfqlc36dw0000gn/T/ipykernel_3549/2543802636.py\", line 50, in run_bad_task\n    raise TaskError(\"task failed\")\nTaskError: task failed\n"
    }
}